# Generated by Django 5.0.2 on 2024-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
