# Generated by Django 4.2.13 on 2024-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_notes_location_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='notes',
        ),
    ]
