version: "3.9"
services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

  django:
    build: .
    env_file: .env
    depends_on:
      - postgres
    environment:
      - "DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,real.domain.com`"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.development.rule=Host(`127.0.0.1`) || Host(`localhost`)"
      - "traefik.http.routers.development.entrypoints=web"
#      - "traefik.http.routers.production.rule=Host(`real.domain.com`)"
#      - "traefik.http.routers.production.entrypoints=websecure"
#      - "traefik.http.routers.production.tls.certresolver=le-resolver"

  reverse-proxy:
    image: traefik:v2.9
    env_file: .env
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le-resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.le-resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le-resolver.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.le-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres-data:
