version: "3.9"
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

  web:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - "static-data:/var/website/static"
      - "./website:/usr/src/website"
    links:
      - "db:database"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"

  reverse-proxy:
    image: traefik:v2.9
    env_file: .env
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "static-data:/var/website/static:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres-data:
  static-data:
