# Generated by Django 4.2.16 on 2025-02-04 06:13

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("variant", models.CharField(max_length=30)),
                ("active", models.BooleanField(default=True)),
                (
                    "barcode",
                    models.CharField(
                        default=inventory.models.BaseItem.generate_uuid,
                        max_length=36,
                        unique=True,
                        validators=[inventory.models.validate_upc],
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "variant")},
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "base_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.baseitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("base_item", "location")},
            },
        ),
    ]
