# Generated by Django 4.2.16 on 2024-12-12 03:40

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="barcode",
            field=models.CharField(
                default=inventory.models.generate_uuid,
                max_length=36,
                unique=True,
                validators=[inventory.models.validate_upc],
            ),
        ),
    ]
