name: Build Raspberry Pi Image
on: [release]
jobs:
  build:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Raspberry Pi Image
        uses: usimd/pi-gen-action@v1
        with:
            ## Final Image Settings

            image-name: "${{ github.event.repository.name }}-${{ github.event.release.tag_name }}"
            hostname: ${{ github.event.repository.name }}

            # Final image compression method & level (0-9, default 6)
            compression: zip

            compression-level: 6

            # Enable SSH access to Pi.
            enable-ssh: 1

            # Default keyboard keymap.
            keyboard-keymap: gb

            # Default keyboard layout.
            keyboard-layout: English (UK)

            # Default locale of the system image.
            locale: en_GB.UTF-8

            # System timezone.
            timezone: America/New_York

            # Wifi country code of default network to connect to.
            wpa-country: "US"

            ## Pi-Gen Build Settings

            # List of stage name to execute in given order. Relative and absolute paths to
            # custom stage directories are allowed here. Note that by default pi-gen exports
            # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom
            # stages before one of the exported stages. Otherwise, the action will make sure
            # any custom stage will include an image export directive.
            stage-list: stage0 stage1 stage2 ./build-shop

            # Only export the last stage.
            export-last-stage-only: true

            # Pi-gen host dependencies, not affecting the final image which is set in the custom stage.
            extra-host-dependencies: ""

            # Pi-gen host dependencies, not affecting the final image.
            extra-host-modules: ""

            # Token to use for checking out pi-gen repo.
            github-token: ${{ github.token }}

            # Enabling this option will remove plenty of components from the GitHub Actions
            # runner that are not mandatory pre-requisites for a (vanilla) pi-gen build. This
            # shall increase the available disk space so that also large images can be
            # compiled on a free GHA runner (benchmark is the full image including a desktop
            # environment). If any packages are missing during the build consider adding them
            # to the `extra-host-dependencies` list.
            increase-runner-disk-size: false

            # Path where selected pi-gen ref will be checked out to. If the path does not yet
            # exist, it will be created (including its parents).
            pi-gen-dir: pi-gen

            # The release name to use in `/etc/issue.txt`. The default should only be used for
            # official Raspberry Pi builds.
            pi-gen-release: ${{ github.event.repository.description }}

            # GitHub repository to fetch pi-gen from, must be a fork from RPi-Distro/pi-gen.
            pi-gen-repository: RPi-Distro/pi-gen

            # Release version of pi-gen to use.
            pi-gen-version: arm64

            # Disables password authentication for SSH and enables public key authentication.
            pubkey-only-ssh: 0

            # Sets the contents of the FIRST_USER_NAME's ~/.ssh/authorized_keys.
            # Value should therefore be a valid authorized_keys file.
            pubkey-ssh-first-user: ""

            # Valid values are jessie, stretch, buster, bullseye, bookworm, and testing.
            release: bookworm

            # SSID of a default wifi network to connect to.
            wpa-essid: ""

            # Password of default wifi network to connect to.
            wpa-password: ""

            # Print all output from pi-gen.
            verbose-output: true
